import type { User, Tool, Category, Borrowing, ActivityLog, DashboardStats } from "./types"

export const mockUsers: User[] = [
  { id: "1", name: "Admin Utama", email: "admin@example.com", role: "admin", createdAt: "2024-01-01" },
  { id: "2", name: "Budi Santoso", email: "budi@example.com", role: "petugas", createdAt: "2024-01-15" },
  { id: "3", name: "Siti Rahayu", email: "siti@example.com", role: "peminjam", createdAt: "2024-02-01" },
  { id: "4", name: "Ahmad Hidayat", email: "ahmad@example.com", role: "peminjam", createdAt: "2024-02-10" },
  { id: "5", name: "Dewi Lestari", email: "dewi@example.com", role: "peminjam", createdAt: "2024-02-20" },
]

export const mockCategories: Category[] = [
  { id: "1", name: "Elektronik", description: "Peralatan elektronik", toolCount: 15 },
  { id: "2", name: "Pertukangan", description: "Alat pertukangan", toolCount: 25 },
  { id: "3", name: "Laboratorium", description: "Peralatan laboratorium", toolCount: 30 },
  { id: "4", name: "Fotografi", description: "Peralatan fotografi", toolCount: 10 },
  { id: "5", name: "Audio Visual", description: "Peralatan audio visual", toolCount: 12 },
]

export const mockTools: Tool[] = [
  {
    id: "1",
    name: "Laptop Dell XPS 15",
    description: "Laptop performa tinggi untuk presentasi",
    category: "Elektronik",
    categoryId: "1",
    stock: 5,
    available: 3,
    condition: "baik",
    createdAt: "2024-01-01",
  },
  {
    id: "2",
    name: "Proyektor Epson",
    description: "Proyektor HD untuk ruang meeting",
    category: "Elektronik",
    categoryId: "1",
    stock: 3,
    available: 2,
    condition: "baik",
    createdAt: "2024-01-05",
  },
  {
    id: "3",
    name: "Bor Listrik Bosch",
    description: "Bor listrik untuk pekerjaan berat",
    category: "Pertukangan",
    categoryId: "2",
    stock: 10,
    available: 7,
    condition: "baik",
    createdAt: "2024-01-10",
  },
  {
    id: "4",
    name: "Mikroskop Digital",
    description: "Mikroskop dengan kamera digital",
    category: "Laboratorium",
    categoryId: "3",
    stock: 8,
    available: 5,
    condition: "baik",
    createdAt: "2024-01-15",
  },
  {
    id: "5",
    name: "Kamera Canon EOS R5",
    description: "Kamera mirrorless professional",
    category: "Fotografi",
    categoryId: "4",
    stock: 4,
    available: 2,
    condition: "baik",
    createdAt: "2024-01-20",
  },
  {
    id: "6",
    name: "Tripod Manfrotto",
    description: "Tripod profesional untuk video",
    category: "Fotografi",
    categoryId: "4",
    stock: 6,
    available: 4,
    condition: "baik",
    createdAt: "2024-01-25",
  },
  {
    id: "7",
    name: "Speaker Portable JBL",
    description: "Speaker bluetooth untuk acara",
    category: "Audio Visual",
    categoryId: "5",
    stock: 8,
    available: 6,
    condition: "baik",
    createdAt: "2024-02-01",
  },
  {
    id: "8",
    name: "Mixer Audio Yamaha",
    description: "Mixer 12 channel untuk event",
    category: "Audio Visual",
    categoryId: "5",
    stock: 2,
    available: 1,
    condition: "baik",
    createdAt: "2024-02-05",
  },
]

export const mockBorrowings: Borrowing[] = [
  {
    id: "1",
    toolId: "1",
    tool: mockTools[0],
    userId: "3",
    user: mockUsers[2],
    borrowDate: "2024-03-01",
    returnDate: "2024-03-08",
    quantity: 1,
    status: "approved",
    createdAt: "2024-03-01",
  },
  {
    id: "2",
    toolId: "5",
    tool: mockTools[4],
    userId: "4",
    user: mockUsers[3],
    borrowDate: "2024-03-05",
    returnDate: "2024-03-12",
    quantity: 1,
    status: "pending",
    createdAt: "2024-03-05",
  },
  {
    id: "3",
    toolId: "3",
    tool: mockTools[2],
    userId: "5",
    user: mockUsers[4],
    borrowDate: "2024-03-02",
    returnDate: "2024-03-09",
    quantity: 2,
    status: "approved",
    createdAt: "2024-03-02",
  },
  {
    id: "4",
    toolId: "7",
    tool: mockTools[6],
    userId: "3",
    user: mockUsers[2],
    borrowDate: "2024-02-20",
    returnDate: "2024-02-27",
    quantity: 1,
    status: "overdue",
    createdAt: "2024-02-20",
  },
  {
    id: "5",
    toolId: "2",
    tool: mockTools[1],
    userId: "4",
    user: mockUsers[3],
    borrowDate: "2024-03-10",
    returnDate: "2024-03-17",
    quantity: 1,
    status: "pending",
    createdAt: "2024-03-10",
  },
]

export const mockActivityLogs: ActivityLog[] = [
  {
    id: "1",
    userId: "1",
    user: mockUsers[0],
    action: "CREATE_TOOL",
    description: "Menambahkan alat baru: Laptop Dell XPS 15",
    createdAt: "2024-03-01T10:00:00",
  },
  {
    id: "2",
    userId: "2",
    user: mockUsers[1],
    action: "APPROVE_BORROWING",
    description: "Menyetujui peminjaman oleh Siti Rahayu",
    createdAt: "2024-03-01T11:00:00",
  },
  {
    id: "3",
    userId: "3",
    user: mockUsers[2],
    action: "REQUEST_BORROWING",
    description: "Mengajukan peminjaman Laptop Dell XPS 15",
    createdAt: "2024-03-01T09:00:00",
  },
  {
    id: "4",
    userId: "1",
    user: mockUsers[0],
    action: "UPDATE_USER",
    description: "Memperbarui data pengguna Budi Santoso",
    createdAt: "2024-03-02T14:00:00",
  },
  {
    id: "5",
    userId: "2",
    user: mockUsers[1],
    action: "REJECT_BORROWING",
    description: "Menolak peminjaman oleh Ahmad Hidayat",
    createdAt: "2024-03-03T09:30:00",
  },
]

export const mockDashboardStats: DashboardStats = {
  totalTools: 46,
  totalUsers: 125,
  activeBorrowings: 23,
  pendingApprovals: 8,
  overdueItems: 3,
}
